### ISSUE TITLE
Problem segtraining on ALTO and PAGE - can't load the ground truth

### ISSUE THREAD

**Issue by alix-tz** [mittagessen/kraken#191]
Hi, 

Following your responses and explanations in issue #190 I'm trying the new `ketos segtrain` module but I can't load the ground truth and in stead get the following error messages:

#### with PAGE XML format : 
```
Traceback (most recent call last):
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/ketos.py", line 242, in segtrain
    merge_regions=merge_regions)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/lib/dataset.py", line 741, in __init__
    lines[self.mbl_dict.get(line['type'], line['type'])].append(line['baseline'])
KeyError: 'type'
```
after getting almost my whole files listed in error messages such as : 
```
...
[0.0298] Invalid entry "      <TextLine id="eSc_line_1970549">" in /scratch/achague/kraken_upon_cluster/segmentation/data_seg_2/pagexml/VOL04_0009.xml 
[0.0301] Invalid entry "          <Coords points="208,1027 215,991 415,991 426,999 454,989 543,989 575,999 611,989 778,989 808,999 820,989 1068,989 1102,999 1115,991 1249,984 1304,991 1309,1027 1304,1046 1115,1046 1102,1038 1089,1046 810,1038 797,1046 590,1044 577,1035 532,1046 213,1046"/>" in /scratch/achague/kraken_upon_cluster/segmentation/data_seg_2/pagexml/VOL04_0009.xml 
[0.0304] Invalid entry "        <Baseline points="211,1029 1310,1029"/>" in /scratch/achague/kraken_upon_cluster/segmentation/data_seg_2/pagexml/VOL04_0009.xml 
...
```
---

#### with ALTO XML format : 
```
Traceback (most recent call last):
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/ketos.py", line 242, in segtrain
    merge_regions=merge_regions)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/lib/dataset.py", line 741, in __init__
    lines[self.mbl_dict.get(line['type'], line['type'])].append(line['baseline'])
KeyError: 'type'
```

After getting the same messages : 
```
...
[0.0092] Invalid entry "<?xml version="1.0" encoding="UTF-8"?>" in /scratch/achague/kraken_upon_cluster/segmentation/data_seg_2/alto/VOL04_0009.xml 
[0.0103] Invalid entry "<alto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"" in /scratch/achague/kraken_upon_cluster/segmentation/data_seg_2/alto/VOL04_0009.xml 
[0.0110] Invalid entry "	  xmlns="http://www.loc.gov/standards/alto/ns-v4#"" in /scratch/achague/kraken_upon_cluster/segmentation/data_seg_2/alto/VOL04_0009.xml 
[0.0114] Invalid entry "	  xsi:schemaLocation="http://www.loc.gov/standards/alto/ns-v4# https://gitlab.inria.fr/scripta/escriptorium/-/raw/develop/app/escriptorium/static/alto-4-1-baselines.xsd">" in /scratch/achague/kraken_upon_cluster/segmentation/data_seg_2/alto/VOL04_0009.xml 
...
```
---

Here are the commandes : 
- `ketos segtrain -f page --suppress-regions --device cuda:0 --training-files myfiles/*.xml`
- `ketos segtrain -f alto --suppress-regions --device cuda:0 --training-files myfiles/*.xml`

All files were produced using eScriptorium (the version from the EPHE server, to make sure I had the last version).

---

Obviously, I'm doing something wrong here. Any idea how I can fix this?

Many thanks! :octopus:

**Comment by alix-tz** [comment]
Following Daniel's response, I built a list of the XML files in a `allxmls.xmllist` which I then feed to Kraken with the "-t/--training-files" option. This solves the "Invalid entry" problem, but not the final error message: 

```
Traceback (most recent call last):
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/ketos.py", line 242, in segtrain
    merge_regions=merge_regions)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/lib/dataset.py", line 741, in __init__
    lines[self.mbl_dict.get(line['type'], line['type'])].append(line['baseline'])
KeyError: 'type'
```

**Comment by mittagessen** [comment]
Please pull again. There was a merge regression that crept in there. I
fixed that last night.

**Comment by alix-tz** [comment]
Hi Ben,

Here are two errors I receive when I'm trying to load ALTO files for training (I have a very small amount of XML files at the moment since I am mostly trying to set the workflow). I'm still trying to understand with it is still a problem linked to the compatibility between Pytorch and GlibC (which should be solved by now) or if it is linked to the files I'm using or both... Any lead?

Note that, following Daniel's indications, the .xmllist file only contains a list of paths, such as : 
```
path1.xml
path2.xml
path3.xml
```

1. With this command: `ketos train --device cuda:0 -f alto -t path/my_alto.xmllist` :
```
[3.3070] Text line is empty after transformations   (<- repeated a good 450 times)
Usage: ketos train [OPTIONS] [GROUND_TRUTH]...

Error: No valid training data was provided to the train command. Please add valid XML or line data.
```

or 

2. With a command like this one : `ketos segtrain --device cuda:0 -f alto -t path/my_alto.xmllist ` :
```
/lib64/libc.so.6(+0x3c02c75e5e)[0x2aaaaaf61e5e]
/lib64/libc.so.6(+0x3c02c78cf0)[0x2aaaaaf64cf0]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so(+0x1985d)[0x2aab092bf85d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0xfdb08)[0x555555651b08]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed27)[0x555555662d27]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x10ed3d)[0x555555662d3d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x2ac2)[0x555555722172]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallDict+0x10b)[0x55555566a3fb]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x1e9d)[0x55555572154d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x5555556bd02b]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x690)[0x55555571fd40]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x5555556bd02b]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x690)[0x55555571fd40]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x5555556bd02b]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x690)[0x55555571fd40]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallDict+0x10b)[0x55555566a3fb]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyObject_Call_Prepend+0x63)[0x555555689a73]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x17d1ba)[0x5555556d11ba]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyObject_FastCallKeywords+0x128)[0x5555556d1f78]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x4a96)[0x555555724146]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x5555556bd02b]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x4b39)[0x5555557241e9]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x5555556bd02b]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x4b39)[0x5555557241e9]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x5555556bd02b]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x690)[0x55555571fd40]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalCodeWithName+0x5da)[0x55555566966a]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallDict+0x1d5)[0x55555566a4c5]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyObject_Call_Prepend+0x63)[0x555555689a73]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x17d1ba)[0x5555556d11ba]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyObject_FastCallKeywords+0x128)[0x5555556d1f78]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x4a96)[0x555555724146]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x5555556bd02b]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x4b39)[0x5555557241e9]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalCodeWithName+0x5da)[0x55555566966a]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallDict+0x3ff)[0x55555566a6ef]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyObject_Call_Prepend+0x63)[0x555555689a73]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(+0x17d1ba)[0x5555556d11ba]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyObject_FastCallKeywords+0x128)[0x5555556d1f78]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x580b)[0x555555724ebb]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalCodeWithName+0xab8)[0x555555669b48]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallDict+0x3ff)[0x55555566a6ef]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x1e9d)[0x55555572154d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalCodeWithName+0x5da)[0x55555566966a]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallDict+0x3ff)[0x55555566a6ef]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x1e9d)[0x55555572154d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x555555669389]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallDict+0x3ff)[0x55555566a6ef]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyObject_Call_Prepend+0x63)[0x555555689a73]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(PyObject_Call+0x6e)[0x55555567bfde]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x1e9d)[0x55555572154d]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x5555556bd02b]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalFrameDefault+0x690)[0x55555571fd40]
/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/python(_PyEval_EvalCodeWithName+0xab8)[0x555555669b48]
======= Memory map: ========
200000000-600200000 ---p 00000000 00:00 0 
10000000000-10400000000 ---p 00000000 00:00 0 
2aaaaaaab000-2aaaaaacb000 r-xp 00000000 08:01 1128536                    /lib64/ld-2.12.so
2aaaaaacb000-2aaaaaacc000 r-xp 00000000 00:00 0                          [vdso]
2aaaaaacc000-2aaaaaacd000 rw-p 00000000 00:00 0 
2aaaaaacd000-2aaaaab8d000 rw-p 00000000 00:00 0 
2aaaaaccb000-2aaaaaccc000 r--p 00020000 08:01 1128536                    /lib64/ld-2.12.so
2aaaaaccc000-2aaaaaccd000 rw-p 00021000 08:01 1128536                    /lib64/ld-2.12.so
2aaaaaccd000-2aaaaacce000 rw-p 00000000 00:00 0 
2aaaaacce000-2aaaaace5000 r-xp 00000000 08:01 1128446                    /lib64/libpthread-2.12.so
2aaaaace5000-2aaaaaee5000 ---p 00017000 08:01 1128446                    /lib64/libpthread-2.12.so
2aaaaaee5000-2aaaaaee6000 r--p 00017000 08:01 1128446                    /lib64/libpthread-2.12.so
2aaaaaee6000-2aaaaaee7000 rw-p 00018000 08:01 1128446                    /lib64/libpthread-2.12.so
2aaaaaee7000-2aaaaaeec000 rw-p 00000000 00:00 0 
2aaaaaeec000-2aaaab077000 r-xp 00000000 08:01 1128538                    /lib64/libc-2.12.so
2aaaab077000-2aaaab276000 ---p 0018b000 08:01 1128538                    /lib64/libc-2.12.so
2aaaab276000-2aaaab27a000 r--p 0018a000 08:01 1128538                    /lib64/libc-2.12.so
2aaaab27a000-2aaaab27c000 rw-p 0018e000 08:01 1128538                    /lib64/libc-2.12.so
2aaaab27c000-2aaaab280000 rw-p 00000000 00:00 0 
2aaaab280000-2aaaab282000 r-xp 00000000 08:01 1128544                    /lib64/libdl-2.12.so
2aaaab282000-2aaaab482000 ---p 00002000 08:01 1128544                    /lib64/libdl-2.12.so
2aaaab482000-2aaaab483000 r--p 00002000 08:01 1128544                    /lib64/libdl-2.12.so
2aaaab483000-2aaaab484000 rw-p 00003000 08:01 1128544                    /lib64/libdl-2.12.so
2aaaab484000-2aaaab486000 r-xp 00000000 08:01 1128488                    /lib64/libutil-2.12.so
2aaaab486000-2aaaab685000 ---p 00002000 08:01 1128488                    /lib64/libutil-2.12.so
2aaaab685000-2aaaab686000 r--p 00001000 08:01 1128488                    /lib64/libutil-2.12.so
2aaaab686000-2aaaab687000 rw-p 00002000 08:01 1128488                    /lib64/libutil-2.12.so
2aaaab687000-2aaaab688000 rw-p 00000000 00:00 0 
2aaaab688000-2aaaab68f000 r-xp 00000000 08:01 1128541                    /lib64/librt-2.12.so
2aaaab68f000-2aaaab88e000 ---p 00007000 08:01 1128541                    /lib64/librt-2.12.so
2aaaab88e000-2aaaab88f000 r--p 00006000 08:01 1128541                    /lib64/librt-2.12.so
2aaaab88f000-2aaaab890000 rw-p 00007000 08:01 1128541                    /lib64/librt-2.12.so
2aaaab890000-2aaaab913000 r-xp 00000000 08:01 1130520                    /lib64/libm-2.12.so
2aaaab913000-2aaaabb12000 ---p 00083000 08:01 1130520                    /lib64/libm-2.12.so
2aaaabb12000-2aaaabb13000 r--p 00082000 08:01 1130520                    /lib64/libm-2.12.so
2aaaabb13000-2aaaabb14000 rw-p 00083000 08:01 1130520                    /lib64/libm-2.12.so
2aaaabb14000-2aaaabb16000 rw-p 00000000 00:00 0 
2aaaabb16000-2aaab19ab000 r--p 00000000 08:01 853566                     /usr/lib/locale/locale-archive
2aaab19ab000-2aaab19b2000 r--s 00000000 08:01 1234931                    /usr/lib64/gconv/gconv-modules.cache
2aaab19b2000-2aaab1b32000 rw-p 00000000 00:00 0 
2aaab1b57000-2aaab1bd7000 rw-p 00000000 00:00 0 
2aaab1bd8000-2aaab1c58000 rw-p 00000000 00:00 0 
2aaab1c58000-2aaab1c59000 r--p 00000000 00:15 17224574129659165683       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_heapq.cpython-37m-x86_64-linux-gnu.so
2aaab1c59000-2aaab1c5b000 r-xp 00001000 00:15 17224574129659165683       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_heapq.cpython-37m-x86_64-linux-gnu.so
2aaab1c5b000-2aaab1c5c000 r--p 00003000 00:15 17224574129659165683       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_heapq.cpython-37m-x86_64-linux-gnu.so
2aaab1c5c000-2aaab1c5d000 r--p 00003000 00:15 17224574129659165683       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_heapq.cpython-37m-x86_64-linux-gnu.so
2aaab1c5d000-2aaab1c5f000 rw-p 00004000 00:15 17224574129659165683       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_heapq.cpython-37m-x86_64-linux-gnu.so
2aaab1c5f000-2aaab1c61000 r--p 00000000 00:15 11953525218972388961       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
2aaab1c61000-2aaab1c6f000 r-xp 00002000 00:15 11953525218972388961       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
2aaab1c6f000-2aaab1c71000 r--p 00010000 00:15 11953525218972388961       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
2aaab1c71000-2aaab1c72000 r--p 00011000 00:15 11953525218972388961       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
2aaab1c72000-2aaab1c73000 rw-p 00012000 00:15 11953525218972388961       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
2aaab1c73000-2aaab1cf3000 rw-p 00000000 00:00 0 
2aaab1cf3000-2aaab1cf4000 r--p 00000000 00:15 11914331234620731020       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
2aaab1cf4000-2aaab1cf5000 r-xp 00001000 00:15 11914331234620731020       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
2aaab1cf5000-2aaab1cf6000 r--p 00002000 00:15 11914331234620731020       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
2aaab1cf6000-2aaab1cf7000 r--p 00002000 00:15 11914331234620731020       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
2aaab1cf7000-2aaab1cf8000 rw-p 00003000 00:15 11914331234620731020       /scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/ketos.py", line 338, in segtrain
    trainer.run(_print_eval, _draw_progressbar)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/lib/train.py", line 331, in run
    self.model.to(self.device)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/kraken/lib/vgsl.py", line 170, in to
    self.nn = self.nn.to(device)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/scratch/achague/anaconda3/envs/kraken_blla_cuda/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 35198) is killed by signal: Aborted. 
```

**Comment by mittagessen** [comment]
Should be resolved with the samples in the docs.
